<?php
/**
 * PDF monthly report (A4, portrait) built with the bundled FPDF library.
 * Data comes from pfms_report_data() in report_export.php.
 *
 * Note: FPDF's built-in fonts cover Western/Latin text. Characters outside that set
 * (e.g. Urdu, Arabic, CJK) are printed as "?" in the PDF; the Excel export keeps them.
 */

require_once __DIR__ . '/fpdf/fpdf.php';

class PfmsReportPdf extends FPDF
{
    // Palette (matches the app's navy / paper theme)
    const NAVY  = [22, 35, 58];
    const INK2  = [59, 74, 99];
    const FAINT = [124, 135, 155];
    const PAPER = [238, 234, 224];
    const CARD  = [251, 250, 246];
    const LINE  = [216, 209, 191];
    const SOFT  = [230, 224, 210];
    const GAIN  = [63, 109, 82];
    const LOSS  = [166, 59, 46];
    const ACCENT = [224, 86, 91];

    public $monthLabel = '';
    public $preparedFor = '';
    public $generated = '';
    private $bottomLimit = 275;   // content must end above this Y (mm)

    public function __construct()
    {
        parent::__construct('P', 'mm', 'A4');
        $this->SetMargins(15, 15, 15);
        $this->SetAutoPageBreak(false);
        $this->AliasNbPages('{nb}');
    }

    /** UTF-8 -> Windows-1252 (what FPDF's core fonts expect). Unsupported characters become '?'. */
    public static function enc($s)
    {
        $s = (string)$s;
        $s = preg_replace('/[\x00-\x08\x0B\x0C\x0E-\x1F]/', '', $s);
        if (function_exists('mb_convert_encoding')) {
            $o = mb_convert_encoding($s, 'Windows-1252', 'UTF-8');
        } else {
            $o = @iconv('UTF-8', 'Windows-1252//TRANSLIT//IGNORE', $s);
        }
        return $o === false ? '' : $o;
    }

    private function color($fnName, array $c)
    {
        $this->$fnName($c[0], $c[1], $c[2]);
    }

    /* --------------------------------------------------- header / footer -- */

    public function Header()
    {
        if ($this->PageNo() === 1) {
            $this->color('SetFillColor', self::NAVY);
            $this->Rect(0, 0, 210, 36, 'F');
            $this->color('SetFillColor', self::ACCENT);
            $this->Rect(0, 36, 210, 1.2, 'F');

            $this->SetFont('Helvetica', 'B', 9);
            $this->SetTextColor(238, 234, 224);
            $this->SetXY(15, 8);
            $this->Cell(60, 5, self::enc('PFMS  |  Personal Finance Management System'), 0, 0, 'L');

            $this->SetFont('Helvetica', 'B', 20);
            $this->SetTextColor(255, 255, 255);
            $this->SetXY(15, 14);
            $this->Cell(120, 9, self::enc('Monthly Financial Report'), 0, 0, 'L');

            $this->SetFont('Helvetica', '', 12);
            $this->SetTextColor(226, 190, 132);
            $this->SetXY(15, 24);
            $this->Cell(120, 6, self::enc($this->monthLabel), 0, 0, 'L');

            $this->SetFont('Helvetica', '', 8);
            $this->SetTextColor(200, 205, 215);
            $this->SetXY(110, 14);
            $this->Cell(85, 4.5, self::enc('Prepared for: ' . $this->preparedFor), 0, 2, 'R');
            $this->Cell(85, 4.5, self::enc('Generated: ' . $this->generated), 0, 0, 'R');

            $this->SetY(44);
        } else {
            $this->SetFont('Helvetica', 'B', 8);
            $this->color('SetTextColor', self::FAINT);
            $this->SetXY(15, 9);
            $this->Cell(120, 4, self::enc('PFMS  |  Monthly Financial Report  |  ' . $this->monthLabel), 0, 0, 'L');
            $this->color('SetDrawColor', self::LINE);
            $this->Line(15, 14.5, 195, 14.5);
            $this->SetY(20);
        }
    }

    public function Footer()
    {
        $this->color('SetDrawColor', self::LINE);
        $this->Line(15, 285, 195, 285);
        $this->SetFont('Helvetica', '', 7.5);
        $this->color('SetTextColor', self::FAINT);
        $this->SetXY(15, 287);
        $this->Cell(120, 4, self::enc('Generated by PFMS on ' . $this->generated), 0, 0, 'L');
        $this->Cell(60, 4, 'Page ' . $this->PageNo() . ' of {nb}', 0, 0, 'R');
    }

    /* -------------------------------------------------------- primitives -- */

    /** Start a new page if fewer than $h mm remain. */
    public function ensure($h)
    {
        if ($this->GetY() + $h > $this->bottomLimit) {
            $this->AddPage();
        }
    }

    public function sectionTitle($text, $need = 32)
    {
        $this->ensure($need);
        $this->Ln(3);
        $this->SetFont('Helvetica', 'B', 11.5);
        $this->color('SetTextColor', self::NAVY);
        $this->SetX(15);
        $this->Cell(180, 7, self::enc($text), 0, 1, 'L');
        $this->color('SetDrawColor', self::NAVY);
        $this->SetLineWidth(0.4);
        $this->Line(15, $this->GetY(), 195, $this->GetY());
        $this->SetLineWidth(0.2);
        $this->Ln(2.5);
    }

    public function note($text, $italic = true)
    {
        $this->SetFont('Helvetica', $italic ? 'I' : '', 8.5);
        $this->color('SetTextColor', self::FAINT);
        $this->SetX(15);
        $this->MultiCell(180, 4.6, self::enc($text), 0, 'L');
        $this->Ln(1);
    }

    /** Row of summary boxes. $items = [[label, value, [r,g,b] valueColor], ...] */
    public function kpis(array $items)
    {
        $gap = 4;
        $n = count($items);
        $w = (180 - $gap * ($n - 1)) / $n;
        $h = 22;
        $y = $this->GetY();
        foreach ($items as $i => $it) {
            $x = 15 + $i * ($w + $gap);
            $this->color('SetFillColor', self::CARD);
            $this->color('SetDrawColor', self::LINE);
            $this->Rect($x, $y, $w, $h, 'DF');
            $this->color('SetFillColor', $it[2]);
            $this->Rect($x, $y, 1.4, $h, 'F');

            $this->SetFont('Helvetica', 'B', 7);
            $this->color('SetTextColor', self::FAINT);
            $this->SetXY($x + 4, $y + 4);
            $this->Cell($w - 6, 4, self::enc(strtoupper($it[0])), 0, 0, 'L');

            $this->SetFont('Helvetica', 'B', 13);
            $this->color('SetTextColor', $it[2]);
            $this->SetXY($x + 4, $y + 10.5);
            $this->Cell($w - 6, 7, self::enc($it[1]), 0, 0, 'L');
        }
        $this->SetY($y + $h + 2);
    }

    /** Two horizontal bars: income vs expenses. */
    public function compareBars($income, $expenses)
    {
        $max = max($income, $expenses, 0.01);
        $labelW = 24;
        $barMax = 100;
        $y = $this->GetY() + 1;
        $rows = [['Income', $income, self::GAIN], ['Expenses', $expenses, self::LOSS]];
        foreach ($rows as $k => $row) {
            $yy = $y + $k * 10;
            $this->SetFont('Helvetica', '', 9);
            $this->color('SetTextColor', self::INK2);
            $this->SetXY(15, $yy);
            $this->Cell($labelW, 6, $row[0], 0, 0, 'L');

            $this->color('SetFillColor', self::SOFT);
            $this->Rect(15 + $labelW, $yy + 0.8, $barMax, 4.4, 'F');
            $len = $row[1] > 0 ? max(0.8, $barMax * $row[1] / $max) : 0;
            if ($len > 0) {
                $this->color('SetFillColor', $row[2]);
                $this->Rect(15 + $labelW, $yy + 0.8, $len, 4.4, 'F');
            }
            $this->SetFont('Helvetica', 'B', 9);
            $this->color('SetTextColor', $row[2]);
            $this->SetXY(15 + $labelW + $barMax + 3, $yy);
            $this->Cell(50, 6, pfms_money($row[1]), 0, 0, 'L');
        }
        $this->SetY($y + 21);
    }

    /* ------------------------------------------------------------- tables -- */

    private function fit($s, $w)
    {
        if ($this->GetStringWidth($s) <= $w) {
            return $s;
        }
        while ($s !== '' && $this->GetStringWidth($s . '...') > $w) {
            $s = substr($s, 0, -1);
        }
        return $s . '...';
    }

    /** Word-wrap a (Windows-1252) string into lines that fit $w mm with the current font. */
    private function wrap($txt, $w)
    {
        $lines = [];
        foreach (preg_split('/\R/', $txt) as $para) {
            $cur = '';
            foreach (explode(' ', $para) as $word) {
                $try = $cur === '' ? $word : $cur . ' ' . $word;
                if ($this->GetStringWidth($try) <= $w) {
                    $cur = $try;
                    continue;
                }
                if ($cur !== '') {
                    $lines[] = $cur;
                    $cur = '';
                }
                while ($this->GetStringWidth($word) > $w && strlen($word) > 1) {   // very long single word
                    $k = 1;
                    while ($k < strlen($word) - 1 && $this->GetStringWidth(substr($word, 0, $k + 1)) <= $w) {
                        $k++;
                    }
                    $lines[] = substr($word, 0, $k);
                    $word = substr($word, $k);
                }
                $cur = $word;
            }
            $lines[] = $cur;
        }
        return $lines ?: [''];
    }

    private function tableHeader(array $cols, $fs)
    {
        $x = 15;
        $y = $this->GetY();
        $this->color('SetFillColor', self::NAVY);
        $this->Rect(15, $y, 180, 7, 'F');
        $this->SetFont('Helvetica', 'B', $fs - 0.5);
        $this->SetTextColor(255, 255, 255);
        foreach ($cols as $c) {
            $this->SetXY($x + 1.6, $y);
            $this->Cell($c['w'] - 3.2, 7, self::enc($c['t']), 0, 0, $c['a'] ?? 'L');
            $x += $c['w'];
        }
        $this->SetY($y + 7);
    }

    /**
     * $cols: [['t'=>'Title','w'=>mm,'a'=>'L|R|C','wrap'=>bool], ...]   (widths should sum to 180)
     * $rows: list of rows. A row is an array of cells, or ['cells'=>[...], 'total'=>true].
     *        A cell is a string, or ['v'=>string,'c'=>[r,g,b],'b'=>bool,'bar'=>0..1].
     */
    public function table(array $cols, array $rows, $fs = 8.5)
    {
        $lh = 4.6;
        $pad = 1.6;
        $this->ensure(7 + 12);
        $this->tableHeader($cols, $fs);

        foreach ($rows as $row) {
            $isTotal = !empty($row['total']);
            $cells = isset($row['cells']) ? $row['cells'] : $row;

            // measure
            $lines = [];
            $maxLines = 1;
            foreach ($cols as $i => $c) {
                $cell = $cells[$i] ?? '';
                if (!is_array($cell)) {
                    $cell = ['v' => $cell];
                }
                $bold = $isTotal || !empty($cell['b']);
                $this->SetFont('Helvetica', $bold ? 'B' : '', $fs);
                $txt = self::enc($cell['v'] ?? '');
                $lines[$i] = !empty($c['wrap']) ? $this->wrap($txt, $c['w'] - 2 * $pad) : [$this->fit($txt, $c['w'] - 2 * $pad)];
                $maxLines = max($maxLines, count($lines[$i]));
            }
            $h = $maxLines * $lh + 2.4;

            if ($this->GetY() + $h > $this->bottomLimit) {
                $this->AddPage();
                $this->tableHeader($cols, $fs);
            }

            $x = 15;
            $y = $this->GetY();
            if ($isTotal) {
                $this->color('SetFillColor', self::PAPER);
                $this->Rect(15, $y, 180, $h, 'F');
                $this->color('SetDrawColor', self::NAVY);
                $this->Line(15, $y, 195, $y);
            }

            foreach ($cols as $i => $c) {
                $cell = $cells[$i] ?? '';
                if (!is_array($cell)) {
                    $cell = ['v' => $cell];
                }
                $bold = $isTotal || !empty($cell['b']);

                if (isset($cell['bar'])) {                       // proportional bar cell
                    $bw = $c['w'] - 2 * $pad;
                    $this->color('SetFillColor', self::SOFT);
                    $this->Rect($x + $pad, $y + ($h - 2.8) / 2, $bw, 2.8, 'F');
                    if ($cell['bar'] > 0) {
                        $this->color('SetFillColor', $cell['c'] ?? self::NAVY);
                        $this->Rect($x + $pad, $y + ($h - 2.8) / 2, max(0.6, $bw * min(1, $cell['bar'])), 2.8, 'F');
                    }
                } else {
                    $this->SetFont('Helvetica', $bold ? 'B' : '', $fs);
                    $this->color('SetTextColor', $cell['c'] ?? self::NAVY);
                    foreach ($lines[$i] as $k => $ln) {
                        $this->SetXY($x + $pad, $y + 1.2 + $k * $lh);
                        $this->Cell($c['w'] - 2 * $pad, $lh, $ln, 0, 0, $c['a'] ?? 'L');
                    }
                }
                $x += $c['w'];
            }

            $this->color('SetDrawColor', self::LINE);
            $this->Line(15, $y + $h, 195, $y + $h);
            $this->SetY($y + $h);
        }
        $this->Ln(1);
    }
}

/* ---------------------------------------------------------------- builder -- */

function pfms_build_pdf(array $r)
{
    $pdf = new PfmsReportPdf();
    $pdf->monthLabel  = $r['label'];
    $pdf->preparedFor = ($r['user_name'] !== '' ? $r['user_name'] : 'PFMS user') . ($r['user_email'] !== '' ? ' (' . $r['user_email'] . ')' : '');
    $pdf->generated   = $r['generated'];
    $pdf->SetTitle('PFMS Monthly Financial Report - ' . $r['label'], true);
    $pdf->SetAuthor('PFMS', true);
    $pdf->SetCreator('PFMS', true);
    $pdf->AddPage();

    $GAIN = PfmsReportPdf::GAIN;
    $LOSS = PfmsReportPdf::LOSS;
    $NAVY = PfmsReportPdf::NAVY;
    $FAINT = PfmsReportPdf::FAINT;

    $inc = $r['income'];
    $exp = $r['expenses'];
    $sav = $r['savings'];

    /* ---- summary ---- */
    $pdf->kpis([
        ['Total income',   pfms_money($inc), $GAIN],
        ['Total expenses', pfms_money($exp), $LOSS],
        ['Net savings',    pfms_money($sav), $sav >= 0 ? $GAIN : $LOSS],
        ['Savings rate',   $inc > 0 ? number_format($sav / $inc * 100, 1) . '%' : 'n/a', $sav >= 0 ? $GAIN : $LOSS],
    ]);

    $pdf->sectionTitle('Income vs expenses', 40);
    if ($inc == 0 && $exp == 0) {
        $pdf->note('No income or expenses were recorded this month.');
    } else {
        $pdf->compareBars($inc, $exp);
    }

    /* ---- category tables ---- */
    $catCols = [
        ['t' => 'Category',  'w' => 62, 'a' => 'L'],
        ['t' => 'Amount',    'w' => 34, 'a' => 'R'],
        ['t' => '% of total', 'w' => 24, 'a' => 'R'],
        ['t' => 'Share',     'w' => 60, 'a' => 'L'],
    ];
    $catRows = function (array $items, $total, array $color) {
        $rows = [];
        foreach ($items as $name => $amt) {
            $share = $total > 0 ? $amt / $total : 0;
            $rows[] = [
                $name,
                pfms_money($amt),
                number_format($share * 100, 1) . '%',
                ['v' => '', 'bar' => $share, 'c' => $color],
            ];
        }
        $rows[] = ['total' => true, 'cells' => ['Total', pfms_money($total), $total > 0 ? '100.0%' : '0.0%', '']];
        return $rows;
    };

    $pdf->sectionTitle('Spending by category');
    if ($r['expense_cats']) {
        $pdf->table($catCols, $catRows($r['expense_cats'], $exp, $LOSS));
    } else {
        $pdf->note('No expenses recorded this month.');
    }

    $pdf->sectionTitle('Income by category');
    if ($r['income_cats']) {
        $pdf->table($catCols, $catRows($r['income_cats'], $inc, $GAIN));
    } else {
        $pdf->note('No income recorded this month.');
    }

    /* ---- budget vs actual ---- */
    $pdf->sectionTitle('Budget vs actual');
    if ($r['budgets']) {
        $cols = [
            ['t' => 'Category', 'w' => 48, 'a' => 'L'],
            ['t' => 'Budget',   'w' => 28, 'a' => 'R'],
            ['t' => 'Actual',   'w' => 28, 'a' => 'R'],
            ['t' => 'Variance', 'w' => 30, 'a' => 'R'],
            ['t' => '% used',   'w' => 18, 'a' => 'R'],
            ['t' => 'Status',   'w' => 28, 'a' => 'L'],
        ];
        $rows = [];
        $sB = 0; $sA = 0;
        foreach ($r['budgets'] as $b) {
            $over = $b['variance'] < 0;
            $rows[] = [
                $b['category'],
                pfms_money($b['budget']),
                pfms_money($b['actual']),
                ['v' => pfms_money($b['variance'], true), 'c' => $over ? $LOSS : $GAIN],
                $b['budget'] > 0 ? number_format($b['actual'] / $b['budget'] * 100, 0) . '%' : '-',
                ['v' => $over ? 'Over budget' : 'Within budget', 'c' => $over ? $LOSS : $GAIN, 'b' => true],
            ];
            $sB += $b['budget'];
            $sA += $b['actual'];
        }
        $sV = round($sB - $sA, 2);
        $rows[] = ['total' => true, 'cells' => [
            'Total', pfms_money($sB), pfms_money($sA),
            ['v' => pfms_money($sV, true), 'c' => $sV < 0 ? $LOSS : $GAIN],
            $sB > 0 ? number_format($sA / $sB * 100, 0) . '%' : '-',
            ['v' => $sV < 0 ? 'Over budget' : 'Within budget', 'c' => $sV < 0 ? $LOSS : $GAIN],
        ]];
        $pdf->table($cols, $rows);
        $pdf->note('Variance = budget - actual. A negative variance means the category is over budget.');
    } else {
        $pdf->note('No budgets were set for this month.');
    }

    /* ---- investments ---- */
    $pdf->sectionTitle('Investment portfolio (as of ' . $r['as_of'] . ')');
    if ($r['investments']) {
        $cols = [
            ['t' => 'Investment',  'w' => 42, 'a' => 'L', 'wrap' => true],
            ['t' => 'Type',        'w' => 24, 'a' => 'L'],
            ['t' => 'Purchased',   'w' => 23, 'a' => 'L'],
            ['t' => 'Invested',    'w' => 26, 'a' => 'R'],
            ['t' => 'Current',     'w' => 26, 'a' => 'R'],
            ['t' => 'Gain / loss', 'w' => 24, 'a' => 'R'],
            ['t' => 'Return',      'w' => 15, 'a' => 'R'],
        ];
        $rows = [];
        $sI = 0; $sC = 0;
        foreach ($r['investments'] as $iv) {
            $gain = round($iv['current'] - $iv['invested'], 2);
            $rows[] = [
                $iv['name'],
                $iv['type'],
                $iv['date'] !== '' ? date('d M Y', strtotime($iv['date'])) : '-',
                pfms_money($iv['invested']),
                pfms_money($iv['current']),
                ['v' => pfms_money($gain, true), 'c' => $gain >= 0 ? $GAIN : $LOSS],
                ['v' => ($iv['invested'] > 0 ? number_format($gain / $iv['invested'] * 100, 1) . '%' : '-'), 'c' => $gain >= 0 ? $GAIN : $LOSS],
            ];
            $sI += $iv['invested'];
            $sC += $iv['current'];
        }
        $sG = round($sC - $sI, 2);
        $rows[] = ['total' => true, 'cells' => [
            'Total', '', '', pfms_money($sI), pfms_money($sC),
            ['v' => pfms_money($sG, true), 'c' => $sG >= 0 ? $GAIN : $LOSS],
            ['v' => $sI > 0 ? number_format($sG / $sI * 100, 1) . '%' : '-', 'c' => $sG >= 0 ? $GAIN : $LOSS],
        ]];
        $pdf->table($cols, $rows, 8);
        $pdf->note('Portfolio snapshot: cumulative holdings, not limited to ' . $r['label'] . '.');
    } else {
        $pdf->note('No investments recorded.');
    }

    /* ---- transactions ---- */
    $n = count($r['txns']);
    $pdf->sectionTitle('Transactions (' . $n . ')', 30);
    if ($n) {
        $cols = [
            ['t' => 'Date',        'w' => 23, 'a' => 'L'],
            ['t' => 'Type',        'w' => 20, 'a' => 'L'],
            ['t' => 'Category',    'w' => 34, 'a' => 'L'],
            ['t' => 'Description', 'w' => 71, 'a' => 'L', 'wrap' => true],
            ['t' => 'Amount',      'w' => 32, 'a' => 'R'],
        ];
        $rows = [];
        foreach ($r['txns'] as $t) {
            $isInc = $t['type'] === 'income';
            $rows[] = [
                date('d M Y', strtotime($t['date'])),
                $isInc ? 'Income' : 'Expense',
                $t['category'],
                $t['desc'],
                ['v' => $isInc ? '+' . pfms_money($t['amount']) : '-' . pfms_money($t['amount']), 'c' => $isInc ? $GAIN : $LOSS, 'b' => true],
            ];
        }
        $rows[] = ['total' => true, 'cells' => ['', '', 'Total income', '', ['v' => '+' . pfms_money($inc), 'c' => $GAIN]]];
        $rows[] = ['total' => true, 'cells' => ['', '', 'Total expenses', '', ['v' => '-' . pfms_money($exp), 'c' => $LOSS]]];
        $rows[] = ['total' => true, 'cells' => ['', '', 'Net savings', '', ['v' => pfms_money($sav, true), 'c' => $sav >= 0 ? $GAIN : $LOSS]]];
        $pdf->table($cols, $rows);
    } else {
        $pdf->note('No transactions were recorded this month.');
    }

    return $pdf->Output('S');
}
